### ISSUE TITLE
Re-categorization: Implement new layout on homepage and 404 page

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#1047]
## Description
In order to improve content discovery, I want site to have new layout for homepage and 404 page.

## Acceptance criteria
- [x] Updated homepage layout to match mock-up below
- [ ] Updated 404 page

## Notes
- Work dependent on #1048 
- Work can proceed independently of efforts to update content.

## Tasks
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by kimschulke** [comment]
Mock-up to implement is attached.

A few things to note:

- Headings in bold black text are not clickable (i.e. About COVID-19, Symptoms and treatment, etc.)
- Categories below each Heading are clickable (i.e. COVID-19 facts, Spread and transmission, Food and drug safety, etc.)
- Ordering of Categories under each Heading should display as is in mock-up (not alphabetized)
- View More and Load More options should be removed
- Width should remain in line with grey boxes

[Categories Mock-Up 090220 V7.pdf](https://github.com/18F/cv_faq/files/5269957/Categories.Mock-Up.090220.V7.pdf)
