### ISSUE TITLE
Update meta titles to remove CDC-specific wording

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#337]
We need to change meta data title, logo_alt, and description to CDC agnostic
- [x] For title change "CDC COVID-19 Answers"
to "COVID-19 Answers"
- [x] logo_alt: Suggestion: Change "Home - Find answers about Coronavirus (COVID-19) from the CDC." to "Home - Find answers about Coronavirus (COVID-19) from across the U.S. government."
- [x] Description: Change "CDC works 24/7 to protect America from health, safety and security threats" to "Find information about coronavirus (COVID-19) from across U.S. government"
