### ISSUE TITLE
Adds new CDC  FAQs for Symptoms & Testing (via tracker)

### ISSUE THREAD

**Issue by Mtcarp** [18F/cv_faq#516]
Our content monitoring tool picked up 3 new questions added under symptoms and testing:
<img width="1389" alt="Screen Shot 2020-04-16 at 10 09 05 AM" src="https://user-images.githubusercontent.com/59617356/79467642-fdb7ef00-7fcb-11ea-83d8-34a6f753235a.png">

**Comment by thebestsophist** [comment]
- [x] added to airtable
- [ ] audit for timeliness, stability, etc
- [ ] identified potential overlaps
