### ISSUE TITLE
Update styling to align more with coronavirus.gov

### ISSUE THREAD

**Issue by allisonnorman** [18F/cv_faq#562]
## Description
We have some design changes from TM to align faq.coronavirus.gov more stylistically to coronavirus.gov. 

## Notes
Figma: https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-%5BExternal-Share%5D?node-id=0%3A1

[Preview link
](https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/tm-styling-updates/)
Note: We have tried to capture the changes Tyler went through in the meeting, but it's possible I have missed a few things. It is worth taking another look side by side against the prototype to see if any other changes are not reflected here while we wait for the change log. 

## Acceptance Criteria
- [x] Remove "Coronavirus FAQ Answers from across the U.S. government" in top left on header on current prod version, to match Figma design
- [x] Header - Increase size of logos in header on desktop and mobile and update based on removal of the white banner (logos should have blue background) ([Figma](https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-External-Share?node-id=364%3A3))
- [x] On desktop, update global (non-home page) header ([Figma](https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-External-Share?node-id=409%3A4152))
- [x] On mobile view, update global (non-home page) header ([Figma](https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-External-Share?node-id=390%3A312))
- [x] Update font stack to use open sans extra bold, instead of open sans bold, matching Figma (new words are bolded)
- [x] Top questions section has changed. There is now a background color and no border, and the background color, text color, and color of icons has changed
- [x] "We made things a little bigger" - we should probably check font sizes against Figma to see if other elements have increased
- [x] In the two highlighted boxes (how to protect yourself and what to do if you feel sick) on desktop and mobile, the view all button style has been updated, text weight has changed, and background colors have changed
- [x] Update hover states for top questions and on text boxes (Tyler made it sound like the colors may have changed)
- [x] Update hyperlink and hover color on top categories questions
- [x] PENDING: TM will share an update that includes a contextual signal that a user has transitioned away from coronavirus.gov

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by Mtcarp** [comment]
@allisonnorman Per our convo during afternoon huddle, here's what would be some "definition of done" criteria:
Approved and merged from content administrator
Merged to production by engineer
Notified agency content lead that content is published
Closes issue on the board ([auto-closing an issue](https://help.github.com/en/enterprise/2.16/user/github/managing-your-work-on-github/closing-issues-using-keywords))

**Comment by thomhalla** [comment]
Notes on https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/tm-styling-updates/

- [ ] Please make "Find answers about Coronavirus" align with the beginning of the search bar and the end of the search button as per the design in Figma.

- [ ] Please match "Top questions" font and case with Figma

- [ ] Please ensure > symbol is the same font and font-weight where used

- [ ] Please ensure button corners have same degree of rounding as in Figma ( currently are more rounded)

- [ ] On secondary page, please align   the search bar and title with the content, as per Figma
- [ ] On secondary page please use darker blue for Search button as per Figma

**Comment by thomhalla** [comment]
Additional notes on styling:
- [ ] Remove the border on the search bar.

- [ ] The "Search" button on the search bar should be Open Sans Bold, not Regular.

- [ ] Single question page: hyperlink the H1 "Find answers about coronavirus" to the faq.coronavirus.gov homepage. 

- [ ] Desktop: Hover for "View all" button in the two grey boxes should keep the text white.

- [ ] The "View all" button in the two grey boxes should be Open Sans Bold, not Regular. 

- [ ] The "View all questions »" text under each category should be Open Sans Bold, not Extrabold. 

- [ ] The "Load more questions" button should be Open Sans Bold, not Regular.

- [ ] Add 10px more space above the "Load more questions" button

- [ ] On hover of the Facebook button in the footer, there's a grey line showing up in the bottom right corner.

**Comment by brandocalrissian** [comment]
From the Monday meeting:

- Move update typeahead ACs to another issue
- Strike the loading state AC

**Comment by brandocalrissian** [comment]
More notes:

- Strike "Documentation is complete" from definition of done 
- TODO: @brandocalrissian check with @lauraGgit to see what form of automated accessibility scans we have in the current setup related to our current definition of done

**Comment by brandocalrissian** [comment]
removing these per [decision in meeting](https://github.com/18F/cv_faq/issues/562#issuecomment-620083613):

- [ ] Update typeahead dropdown to bold string being searched on
- [ ] Update typeahead to display "No results for "abcdefg""

**Comment by brandocalrissian** [comment]
For automated accessibility scans today (follow up from [here](https://github.com/18F/cv_faq/issues/562#issuecomment-620087652)), not much.

The CircleCI tests includes HTMLproofer for some basics: https://github.com/18f/cv_faq#automated-testing

Essentially it makes sure images have alt tags.

**Comment by brandocalrissian** [comment]
removing this AC per [decision in meeting](https://github.com/18F/cv_faq/issues/562#issuecomment-620083613):

- [ ] Add Loading State view when "Load more questions" button is pressed

**Comment by brandocalrissian** [comment]
removing this from Definition of Done per [meeting discussion](https://github.com/18F/cv_faq/issues/562#issuecomment-620087652):

- [ ] Documentation is complete

**Comment by brandocalrissian** [comment]
https://github.com/18F/cv_faq/pull/577 was approved and implements this issue.

**Comment by brandocalrissian** [comment]
And it got merged in [this PR](https://github.com/18F/cv_faq/pull/621)
