### ISSUE TITLE
Typeahead styling

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#625]
## Description
- _What is the problem we're trying to solve?_
Improve visualization of search term entered

## Acceptance Criteria
- Update typeahead dropdown to bold string being searched on
- Update typeahead to display "No results for "abcdefg""

## Tasks
- [x] PO approved
- [x] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup

- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment

**Comment by danielnaab** [comment]
Implemented in https://github.com/18F/cv_faq/pull/630

**Comment by jonadecker** [comment]
Should this issue be closed @danielnaab or are you still refining it?

**Comment by danielnaab** [comment]
@jonadecker yep, closing
