### ISSUE TITLE
Update CDC travel FAQs (with partner approval)

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#627]
## Description
There are several changes to [CDC's travel FAQs](https://www.cdc.gov/coronavirus/2019-ncov/travelers/faqs.html) and [U.S. travel guidance](https://www.cdc.gov/coronavirus/2019-ncov/travelers/travel-in-the-us.html).

![Change log for travel questions, including General, Domestic, International, and air and cruise travel](https://user-images.githubusercontent.com/32855580/80636817-e1c43c80-8a12-11ea-9312-f4f5b2629ac3.png)

## Definition of Done
- [x] Received approval from partner agency contact
- [x] Approved and merged from content administrator
- [x] Merged to production by engineer
- [x] Notified agency content lead that content is published

**Comment by jonadecker** [comment]
Addressed in latest revisions doc from CDC
