### ISSUE TITLE
Update FDA FAQs (with partner approval)

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#628]
## Description
FDA has updated, removed, and added FAQs within the past week.

**7 rows changed**
 Question: Q: What is coronavirus disease 2019 (COVID-19)?
 Question: Q: Are there any FDA-approved drug products or medicines to treat COVID-19?
 Question: Q: Are chloroquine phosphate or hydroxychloroquine sulfate approved by the FDA to treat COVID-19?
 Question: Q: May health care providers prescribe chloroquine phosphate or hydroxychloroquine sulfate off-label to treat patients with COVID-19?
 Question: Q: Are there any tests that I can purchase to test myself at home for COVID-19?
 Question: Q: Can I get the coronavirus from food, food packaging, or food containers and preparation area?
 Question: Q: Is the U.S. food supply safe?
**3 rows added**
 Question: Q: Can disinfectant sprays or wipes be used on my skin, injected, inhaled, or ingested to prevent or treat COVID-19?
 Question: Q: Am I at risk for serious complications from COVID-19 if I smoke cigarettes?
 Question: Q: If I vape tobacco or nicotine am I at risk for complications from COVID-19?
**3 rows removed**
 Question: Q: Can disinfectant sprays or wipes be used on my skin to prevent spread of COVID-19?
 Question: Q: How do I know if I’m an essential worker during the COVID-19 pandemic?
 Question: Q: Who should I contact with questions about essential employees or FDA-regulated products traveling through areas with curfews and restrictions because of the coronavirus?

## Definition of Done
- [ ] Received approval from partner agency contact
- [ ] Approved and merged from content administrator
- [ ] Merged to production by engineer
- [ ] Notified agency content lead that content is published
