### ISSUE TITLE
Add bold to Open Sans font

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#629]
## Description
The designs stipulate usage of extrabold in some places, and bold in others. The font in use currently only includes normal and extrabold.

This task is to add in bold and changes styles to use it, where appropriate. Also, go over all the current styling to make sure nothing is inadvertently switched from extrabold to bold.

## Acceptance Criteria
- [x] Extrabold and bold are used as per the current design - https://www.figma.com/file/Qm6suNoOYjYNIY3LWdneEI/FAQ.coronavirus.gov-%E2%80%94-Production-File-%5BExternal-Share%5D?node-id=0%3A1

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by danielnaab** [comment]
Implemented in: https://github.com/18F/cv_faq/pull/630
