### ISSUE TITLE
Add 9 new CDC FAQ questions (with partner approval)

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#631]
## Description
CDC has added a new section to the FAQ.
![Cleaning and disinfecting FAQ section with 9 questions](https://user-images.githubusercontent.com/32855580/80648291-c5310000-8a24-11ea-840e-5ad1c81f9847.png)

## Definition of Done
- [ ] Get approval from partner agency
- [ ] Approved and merged from content administrator
- [ ] Merged to production by engineer
- [ ] Notified agency content lead that content is published

**Comment by vbitzer** [comment]
@brentryanjohnson will communicate about this with our partner tomorrow.

**Comment by janeopm** [comment]
These FAQs have their own CDC category/header assigned (ie, Cleaning and Disinfection): https://www.cdc.gov/coronavirus/2019-ncov/faq.html  Shall I assign where these go within the list of existing categories or does this need to be deliberated before I do? Assuming these would go within protect-yourself and keeping-home-safe. Does this sound correct?

**Comment by brentryanjohnson** [comment]
Yes, I think most of these fit nicely within our current IA, @janeopm. "Should outdoor playgrounds..." could go under "Parents and children."

The only one that doesn't fit neatly is the "sidewalks and roads" FAQ. We can talk about that one later today.
