### ISSUE TITLE
Several CDC changes: 'serology' to 'antibody'

### ISSUE THREAD

**Issue by brentryanjohnson** [18F/cv_faq#633]
## Description
CDC has made several edits, changing "diagnostic" to "viral," and "serology" to "antibody."

![several instances of changing serology to antibody](https://user-images.githubusercontent.com/32855580/80766161-9c2e6f00-8af9-11ea-8604-496fca687b4b.png)

## Definition of Done
- [x] Get partner agency approval
- [x] Approved and merged from content administrator
- [x] Merged to production by engineer
- [x] Notified agency content lead that content is published

**Comment by jonadecker** [comment]
Addressed in latest revisions from CDC
