### ISSUE TITLE
PR template for deployment of content changes

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#649]
## Description

To provide a streamlined content deployment process, add a PR template with a checklist, so we can ensure that content editors and engineering are all on the same page for deployment.

## Acceptance Criteria
- [ ] PR template merged to master
- [ ] Engineers approve PR
- [ ] Content editors approve PR

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment
