### ISSUE TITLE
Add Slack notifications for Github activity

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#650]
As a CV-19 team member, I would like to be kept notified of deployments and Github activity.

To accomplish this, add Slack notifications to the appropriate channel.

Questions:
- Should we limit notifications to just PR merges?

## Acceptance Criteria
- [ ] Notifications active
- [ ] Comment on issue what notifications are wired up

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by brandocalrissian** [comment]
I _think_ I configured the slack/GH integration to notify about PRs.
