### ISSUE TITLE
Implement branching / merging strategy

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#653]
## Description

As a FAQ team member I would like a predictable content and design workflow, and other team members on the same page as myself.

The git workflow would entail:

* New design and content work branched off `master` (production)
* When approved via PR, content merged into `content-preview` (approved content) or `preview` (approved dev/design changes) 
* After merged into the preview branch, a PR created and engineers made reviewers
* At scheduled time windows, an engineer will merge approved content to master

Ideally both kinds of PRs could be covered by the same PR template created via #649 

## Acceptance Criteria
- [x] master branch is made the default branch
- [x] dev branch removed
- [x] content-preview branch created

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment
