### ISSUE TITLE
Audit git branches

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#654]
## Description

As an FAQ contributor, I would like to have a clear understanding of all on-going work in the FAQ project.

## Notes

There are a number of git branches that are unused or otherwise don't have PRs associated with them. This ticket is to go over them and do cleanup, and increase understanding of prior work done and determine if it should continue.

## Acceptance Criteria
- [x] Unused branched removed
- [x] PRs created for branches with work that should continue
- [x] Comment on this issue with action taken for each branch; include link to the HEAD revision for deleted branches, for future reference

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by danielnaab** [comment]
This is a WIP list of each branch and the action taken with it. If there is an existing PR for a branch, it is linked next to it. If there is not a PR for a branch, a link to the HEAD revision of the branch is provided.

# Has closed PR

These branches were deleted, as they have closed pull requests. Each may be restored by following the link to the PR:

* agency-auto-footer #617
* 271 #278
* an-updatetext2 #240
* cms/categories/test-pr #538
* cms/posts/2020-03-21-test2 #236
* cms/posts/2020-03-21-what-is-the-rate-of-infection-in-the-united-states #235
* content-3-20 - #186
* hjb/add-treasury-sba-logos #398
* sg-typeahead #178
* treasury-update-3-31 #395

# No unique commits

* content https://github.com/18F/cv_faq/commit/ea3f35ff2ee107600fc7d4327548e78888020436

# No action taken yet

* add-openapi-spec
* agency-pages
* agency-sort
* allisonnorman-issue-templates
* an-updatetext2
* bh-sort-homepage-1
* cdc-4-15
* cdc-4-16
* cdc-4-23
* cdc-4-27
* cdc-5-6
* cdc-update-4-23
* cdc-updates-4-6
* CDC-5-6-20
* HEAD -> origin/dev
* add-openapi-spec
* agency-auto-footer
* agency-pages
* agency-sort
* allisonnorman-issue-templates
* bh-sort-homepage-1
* cdc-4-15
* cdc-4-16
* cdc-4-23
* cdc-4-27
* cdc-5-6
* cdc-update-4-23
* cdc-updates-4-6
* cdc-updates-revisions-04-30
* cms/animals/to-be-delted
* cms/posts/2020-03-21-what-is-the-rate-of-infection-in-the-united-states #235
* content-3-18
* content-3-21
* content-3-23
* content-3-24
* content-3-25
* content-edits
* content-edits-va-2
* content-treasury-4-2
* data-file-update
* demo
* dependabot/npm_and_yarn/jquery-3.5.0
* dependency-bump
* dev
* fda-4-15
* fda-new-4-21
* fda-updates-05.07.20
* fix-external-content-links
* g-tag-m
* google-tag-manager
* integrated-content
* landing
* link-to-source
* list-items-4-23
* load-more-tweak
* load_test
* master
* move-banner-maybe
* netlify-cms-test
* package-updates
* pr-template
* preview
* preview-content
* recat
* remove-dap
* remove-elements
* school-3-30
* sources-wip-jk
* tags-1
* thomhalla-patch-1
* title-404
* tm-styling-updates
* tom-branch
* unfurl-better
* update-json-sources-schema
* va-content-04-27
* vbitzer-patch-1
* vbitzer-patch-2
* vbitzer-patch-3
* vbitzer-patch-4
* vbitzer-patch-5
* vbitzer-patch-6
