### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#709]
## Description
Snyk has been added to the repo, but it is opening messy PRs. To get us up-to-date, manually upgrade all dependencies.

## Acceptance Criteria
- [x] Snyk auto-closes existing PRs

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment
