### ISSUE TITLE
SPIKE: investigate timeouts in CircleCI

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#720]
## Description

_We're seeing a lot of failed CircleCI tests in both htmlproofer (errant 404s), and jest (timeouts)_

_This prevents us from quickly merging and pushing changes into production as we troubleshoot those error messages, making us less responsive to our task force clients and ultimately the public consuming the website._

_We'll explore configuring retries for specific tests within CircleCI in an effort to prevent spurious test failures, and get a better understanding of why so many timeouts are occurring._

_We'll know this effort is successful when we see a lessening of spurious failures that need to be manually disproven._

## Notes
[Additional context, known dependencies, blockers, links to design documents, etc]

## Acceptance Criteria
- [ ]

## Tasks
- [x] Test circleci workflow locally @piascikj 
- [x] Investigate increasing timeout @piascikj 
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by piascikj** [comment]
Made some updates to the htmlproofer configuration
```ruby
HTMLProofer.check_directory("./_site", {
    empty_alt_ignore: true,
    url_swap: {
      # treat urls to faq.coronavirus.gov as local
      'https://faq.coronavirus.gov' => ''
    },
    # Added this section
    :typhoeus => {
      :connecttimeout => 30, # increased from default of 10 seconds
      :timeout => 60, # increased from default of 30 seconds
    },
    :hydra => { 
      :max_concurrency => 10 # decreased from default of 200
    }
  }).run```

**Comment by danielnaab** [comment]
How much does the concurrency change slow things down?

**Comment by piascikj** [comment]
not at all
