### ISSUE TITLE
SPIKE: actionable search metrics for partners (investigate search, analytics implementation)

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#721]
## Description

As content admin in order to better understand and improve the users's site experience, I need to capture click data in both search results as well as when navigating category pages. 

## Notes

_We'd like to be able to provide actionable intelligence to our Task Force partners on how their FAQs are performing both in site search as well as in site browsing._

_This is not currently possible because of limitations in reporting click-thru data when using the search.gov API, and because of the way accordions are implemented for questions on category pages?_

_We'd like to explore options to enhance results tracking in both search.gov and analytics to gain better understanding of how users are currently navigating the site by browsing and/or searching_

_We'll know we've made headway into solving this when we are able to see CTR in the search admin console, and discrete questions clicked on from category pages in Google Analytics_

## Acceptance Criteria
- [x] Comment with outcome of spike

## Tasks
- [ ] PO approved
- [ ] ~~Usability tested~~

## Definition of Done
- [ ] ~~Pull requests meet technical definition of done~~
- [ ] ~~Code is properly styled per USWDS~~
- [ ] ~~Finished design has been compared against mockup~~
- [x] Documentation is complete
- [ ] ~~CircleCI tests have passed~~
- [ ] ~~Automated accessibility scans have passed~~
- [ ] ~~Manual accessibility testing completed~~
- [ ] ~~Code has been successfully built and deployed into a staging (dev) environment~~

**Comment by jonadecker** [comment]
In speaking with Dawn M, we've learned of an imminent update to capturing and reporting click-thru data for search.gov API users. We plan on moving forward with exploring options to better capture site navigation paths, potentially through event tracking on question accordion click.

**Comment by danielnaab** [comment]
Additionally, on the Google Analytics side, we can track page chapter/hash changes with a configuration change in Google Tag Manager.

Currently, we are not changing the page hash on click events. A follow-up task is to implement that as well as fix incorrect behavior that was introduced at some point, where previous accordion items are not closing when new ones are opened.

**Comment by danielnaab** [comment]
Two tickets were created to implement additional analytics:

* #722 - tracking accordion clicks. Analytics Logic has been contacted - pending work on their end, this will be done
* #757 - search.gov click tracking. awaiting official approach from search.gov team
