### ISSUE TITLE
Track FAQ accordion clicks in Google Analytics

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#722]
## Description

As a FAQ content manager, I would like actionable analytics on what questions are seeing the most interest. To help achieve that, I would like tracking for each FAQ click available in Google Analytics / DAP.

## Notes

* This came out of #721 
* Testing this will require coordinating with Analytics Logic, the manager of the Google Tag Manager account.
* We can implement this by setting the page chapter when each question is clicked.
* Open question: do we want the default behavior of bringing selected chapters to the top of the page, or simulate chapters by using history pushState?

## Acceptance Criteria
- [ ] Selected questions are visible in Google Analytics

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
Analytics Lab implemented a distinct event to track accordion clicks on June 5, 2020.  Seeing data in Google Analytics as of that date.
