### ISSUE TITLE
Search: Implement Routed Queries

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#736]
As a user, I want to see the best search results even if I use a misspelling of a common term or don't use a term that would produce valid results. Example: When I search for "stimulas" I want to see "economic impact payment." 

## Acceptance Criteria
- User can see what they searched for in the search input field
-  User can see that we didn't find matches for their searched term
-  User can see that we're displaying search results for a related term
-  User can see number of matches for related term, up to 50 results (if there are more than 50, we will only show first 50) 
-  User will not see any highlighted search terms in the search results

## Tasks

- [x] Identify terms to test routed queries
- [x] Configure search.gov for routed queries
- [x] Configure API to pull in routed queries. 
- [x] Write copy for routed query search results (@kimschulke )
- [x] Design what user sees for routed query search results
- [x] Implementing dynamic counts for search result
- [x] Populate/retain search term in search box after search is executed
- [x] Implement explanation text to only show when routed queries are displayed 

## Note 

- Create separate story for what we plan to do to track/analyze results of routed queries

## Definition of Done

- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup / vetted by designers
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment
- [x] Usability has been validated on multiple devices
- [ ] PO has verified AC is complete

**Comment by debjudy** [comment]
@danielnaab We have successfully set up routed queries on search.gov for 4 separate groups.  Per Jona, we need the API updated to recognize these queries.

**Comment by uxforgood** [comment]
Text to display when user sees routed query search results: 

**Search Results (#)** 

We’re sorry! We didn't find any results for “router search terms.”

However, we found [#] results for the related term “related term.”
