### ISSUE TITLE
Search: Provide context on SERP when results returned.

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#737]
As a search user in order to have some context on the search results returned, I want to see the term that I searched for and context around results including number of results returned. 

## Notes
When using routed queries, we want to clarify for the user that they searched for "X" but we returned search results of "Y" because of "Z"

## Acceptance Criteria
- [ ] Provide language which helps with clarity
- [ ] Design provided for rendering on SERP

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment
