### ISSUE TITLE
Search: Index Social Links from Footer

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#738]
As a content manager in order to provide more relevant search results, I want to index the social channels that are linked in the site footer. 

## Notes
search.gov provides the ability to index YouTube, Twitter and Flickr.  We would like to experiment with YouTube and Twitter. Possibility of also working with search.gov to integrate Instagram into their index.   

Expect that we need approval from client to integrate these additional content sources into the search results. 

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by janeopm** [comment]
I would limit to authoritative sources on the CDC COVID Channel YouTube right now to see how often/useful these sources actually are to those searching the site.
