### ISSUE TITLE
Improve browser support

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#745]
## Description
We're using ES6/ES7 features on the FAQ. To support older browsers, minimally IE11, we should use a lower common denominator Javascript.

## Notes
* 4% of site users are on IE11
* < 0.01% IE pre-11
* Edge is 5.71%

## Acceptance Criteria
- [x] No JS errors on IE11

## Tasks
- [ ] PO approved
- [ ] ~~Usability tested~~

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [ ] ~~Finished design has been compared against mockup~~
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [ ] ~~Manual accessibility testing completed~~
- [x] Code has been successfully built and deployed into a staging (dev) environment
