### ISSUE TITLE
Explore alternative/better type ahead functionality

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#749]
As a user I want to have a more seamless experience between type ahead and search.gov results page so the things I'm typing ahead match what it's showing me. The results (from search.gov) don't always have the same results as the typeahead (from the site map).

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
closing because addressing with other issues #881
