### ISSUE TITLE
Search: Improve no search results experience

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#750]
## Description
As a search user in order to understand why my search returned no results, I want information that will help me improve my search. 

## Acceptance Criteria
- [ ] Provide language which provides clarity
- [ ] SERP updated with language for when no search results returned.

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
Unable to add back to project board.  Closed issue and opened new issue #811
