### ISSUE TITLE
Communicate Content Authoritativeness

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#751]
As a user, I want to be confident that the content is authoritative and still current. 

## Assumptions
We are empowered to ensure that task force partners have reviewed content relatively recently.

## Acceptance Criteria
- [ ] User can view messaging that the content is still current or has recently been reviewed. 
- [ ] Content team knows how to and can update the reviewed date for each question. 
- [ ] Content team has established a process for regular review of the content (X time).
- [ ] Content team has define default starting state (if an agency has not review). (For example, if there is no value set, it won't display.)

## Tasks
- [ ] Develop approaches to run by PO
- [ ] Usability tested
- [ ] Present options to Tom (mock up)
- [ ] PO approved
- [ ] Talk to content owners and establish review plan
- [ ] Data gathered (affirmative review by agency partners)
- [ ] Change template to support
- [ ] Add data to repo

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by janeopm** [comment]
how do we negotiate between last reviewed vs. last updated and should we?

**Comment by brandocalrissian** [comment]
Content team huddle Monday— discuss w/Jane there about how to engage with content partners— what should that process look like?

This is something we need to engage w/Tom on.

**Comment by brandocalrissian** [comment]
Intent of this ticket is to cover

- developing process for engaging with content partners
- getting approval from Tom to add this to the app
- user research to determine how this should be
- implementing

**Comment by debjudy** [comment]
Kim presented findings from user research.  Recommendations

- Spell out the agency names.  To do with issue #873 
- Having more than 1 date is confusing. 
- Reviewed was the most clear.  Need to discuss implementation.

**Comment by debjudy** [comment]
Concluded that there isn't a better approach to how we are presenting date on content; therefore, closing ticket. A new ticket can be opened in future should a new idea arise.
