### ISSUE TITLE
Search: Experiment with Best Bets

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#752]
As a content administrator in order to highlight the best response, I want to use search.gov best bet functionality.  

## Notes
This could be used to bring in onsite content or source external content. 

## Acceptance Criteria
- [ ] tbd

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by maomeara63** [comment]
Dan,

Can we try testing this with a couple of real examples? 

Search: Testing
Best Bet: https://faq.coronavirus.gov/symptoms-and-testing/should-i-be-tested-for-covid-19/

Search: Tested
Best Bet: https://faq.coronavirus.gov/symptoms-and-testing/should-i-be-tested-for-covid-19/

Search: Higher Risk
Best Bet: https://faq.coronavirus.gov/underlying-conditions/who-is-at-higher-risk-for-serious-illness-from-covid-19/

I think this will provide a better expression of the use cases. Thanks!

**Comment by danielnaab** [comment]
You can try here: https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/best-bets/search/?query=tested

Also, feel free to edit the "best bets" entries in the search.gov admin interface.

**Comment by debjudy** [comment]
Meghan and Kim will look for additional examples where there is a distinction between curated and algorithmic content.  

Kim will generate some options for us to style the page differently. 

Dan - thoughts on how results return same content twice - e.g.  (https://cg-dae9433e-23a0-46d7-bafb-dc79d2d3756c.app.cloud.gov/preview/18f/cv_faq/best-bets/search/?query=tested)

**Comment by kimschulke** [comment]
I suggest:
- smaller font
- more seamless integration of recommended content and search results (potentially remove "search results" header)
- use text such as "recommended by faq.coronavirus.gov" or something similar

Here are a few examples of design: 

- https://search.goarmy.com/search?utf8=%E2%9C%93&affiliate=goarmy&query=enlist&commit.x=0&commit.y=0

- https://search.usa.gov/search?query=razor&submit.x=0&submit.y=0&affiliate=tsa.gov

- Manual from search.gov: https://search.gov/manual/best-bets.html

**Comment by kimschulke** [comment]
Team reviewed 6 mock-ups for design/display of best bets. 

Moving forward with best bets included in Search Results but, outlined with a light grey box. One thing to note is that best bets are not included in the search results total/display count.
