### ISSUE TITLE
Evaluate and recommend change to categorization

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#753]
We have looked at a couple of alternative categorization approaches for the site.  Looking for a recommendation on what to move forward with. 

## Notes
Work was done in late April with Abbey and Natalie on an alternative approach.  We also have looked at research done by Gerry McGovern. 

## Acceptance Criteria
- [ ] tbd

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by brandocalrissian** [comment]
there's a meeting on monday to understand what has happened before

**Comment by brandocalrissian** [comment]
we have a proposal to take to user testing (dot com?)

We have something to test. We want to learn.

**Comment by kimschulke** [comment]
We are conducting two click-tests to assess current and alternative categorization options.

**Comment by debjudy** [comment]
Analysis of initial test results indicate that proposed is better than current.  Working with OW to get more participants to increase confidence in results.  

We will conduct a second test on additional changes to proposed based upon analysis of prior tests results.

**Comment by kimschulke** [comment]
Made improvements to the proposed categorization based on results of the first click-test and general content/SEO suggestions. User testing on the improved version will begin today.

**Comment by kimschulke** [comment]
Completed two rounds of user testing:
- compared current categories vs. revised categories
- used data to improve clarity of category names
- compared revised categories vs. proposed categories

Summary of user testing here:
https://drive.google.com/file/d/1WZ3UiPTu0HUQ6QGT7AK6WgpjiQEDizlm/view?usp=sharing

**Comment by debjudy** [comment]
Approved to move forward on 9/9.
