### ISSUE TITLE
Add search.gov tracking of search result clicks

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#757]
## Description
As a content producer, I would like to know which search results are being clicked with various search terms, so I can tailor content and the search experience to real-world user needs.

## Notes
We can currently track these searches via the hosted search.gov HTML, but do not have the requisite http POST-back available when using the search API. Search.gov is in the process of adding an officially supported Javascript approach to tracking these via the API, which we can integrate in.

This ticket is awaiting completion of said search.gov API tracking capability.

## Acceptance Criteria
- [ ] Analytics of search result clicks visible in search.gov admin interface

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
Checked with Dawn at search.gov.  In progress but not ready yet.  Next action: Tuesday, June 30

**Comment by debjudy** [comment]
Dawn OOO this week.  Follow-up with her next week Tuesday, July 7.

**Comment by brandocalrissian** [comment]
Deb reaching out to Dawn again next week, this might not live too much longer.

**Comment by debjudy** [comment]
7/16 update from Dawn - "We're finalizing it. it turned out there was an impact on our general internal analytics queries that we have to update before we can add this new data source. It's the priority right now, for sure."

Leaving as blocked until have something to test/validate.  Tag to check-in with Dawn again first week of August if no update before then.

**Comment by brandocalrissian** [comment]
Don't do anything on this until a proposal for changing search is denied. Only relevant if staying on search.gov.

**Comment by debjudy** [comment]
8/6 update from Dawn @ search.gov: Item still in queue no targeted completion date provided.

**Comment by debjudy** [comment]
9/16 update from Dawn: Still in queue but no target date yet.

**Comment by brandocalrissian** [comment]
In active discussions with the search.gov team.
