### ISSUE TITLE
Spike: see what having search results in drop down instead of typeahead results looks like

### ISSUE THREAD

**Issue by brandocalrissian** [18F/cv_faq#774]
## Description
Research spike for #749 

## Notes
[Additional context, known dependencies, blockers, links to design documents, etc]

## Acceptance Criteria
- [ ]

## Tasks
- [ ] PO approved
- [ ] ~~Usability tested~~

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [ ] ~~Finished design has been compared against mockup~~
- [ ] ~~Documentation is complete~~
- [ ] ~~CircleCI tests have passed~~
- [x] Automated accessibility scans have passed
- [ ] ~~Manual accessibility testing completed~~
- [x] Code has been successfully built and deployed into a staging (dev) environment

**Comment by danielnaab** [comment]
I'm going to put this in review, and we can track additional work with #774. See #786 for example of search results in the drop-down.

**Comment by brandocalrissian** [comment]
Team to meet next week to discuss what was learned here and next steps

**Comment by danielnaab** [comment]
If we use search.gov results in the autocomplete input, there would be some impacts:

* search.gov analytics will be impacted due to each keypress triggering a service call
* title text of the pages includes site title - that would need to be pruned out
* routed queries need special treatment

There needs to be further discussion on the content-side on if this is a better experience for discovering content.
