### ISSUE TITLE
Remove Netlify

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#780]
## Description

Remove Netlify login page from site.

A older jQuery dependency was flagged from a TTS automated audit on the Netlify entrypoint. Since we don't use Netlify and don't intend to start, let's just remove it.

## Acceptance Criteria
- [x] https://faq.coronavirus.gov/admin/#/ removed

## Tasks
- [ ] PO approved
- [ ] ~~Usability tested~~

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [ ] ~~Finished design has been compared against mockup~~
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [ ] ~~Manual accessibility testing completed~~
- [x] Code has been successfully built and deployed into a staging (dev) environment
