### ISSUE TITLE
Search: Remove category indexing from search.gov

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#783]
As a user in order to get clear results, I want confusing items removed from search results. 

## Notes
Searching for "advil" returns both question and category page in SERP.  

## Acceptance Criteria
- [ ] Category page is no longer visible in SERP.

## Tasks
- [x] Notify search.gov to delist category pages
- [ ] Confirm category pages no longer display in results. 

## Definition of Done
- [ ] PO approved

**Comment by debjudy** [comment]
Request sent to search.gov early week of June 15.  Awaiting confirmation from Dawn.

**Comment by brandocalrissian** [comment]
@jonadecker to follow-up with Dawn today

**Comment by jonadecker** [comment]
Followed up Friday 6-19 and was told this was complete. Upon checking, this does not appear to have been done so reached out again today.

**Comment by brandocalrissian** [comment]
Done as far as we can. If you solve this for search.gov, will likely break external search engines. Manually removing category pages from search results. Can't change the jekyll site map generator (per search dot gov) because it'll break the external search engines.

**Comment by brandocalrissian** [comment]
^^^ todo when we add categories
