### ISSUE TITLE
Styling on old browsers

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#789]
## Description

As a user with an old crusty browser, I would like my experience of navigating FAQ content to be "okay."

## Notes

We're using modern CSS that doesn't style properly on legacy browsers. This is fine, given usage statistics, but as an incremental improvement, post-processing our generated CSS should improve browser support.

* IE10 would benefit likely from autoprefixer and other postcss processors
* Pre-IE10 ??? Test and see what we get

## Acceptance Criteria
- [x] CSS post-processing added
- [x] Comment explaining work done

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment

**Comment by danielnaab** [comment]
Added PostCSS autoprefixer and minification (removal of unused classes).

Styling back to IE10 is working  - IE9 is somewhat okay, IE8 and earlier are very broken.
