### ISSUE TITLE
Search: Update no search result response

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#811]
## Description
As a search user in order to understand why my search returned no results, I want information that will help me improve my search. 

## Acceptance Criteria
- [ ] 

## Tasks
- [x] Provide language which provides clarity
- [x] SERP updated with language for when no search results returned.

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment

**Comment by danielnaab** [comment]
Using this format:

> We’re sorry! We couldn’t find any results for _bananas_.
> Try your search again following these tips:
> * Check your spelling 
> * Try a different keyword
> * Use a more general keyword

**Comment by debjudy** [comment]
Pagination should start at 25.
