### ISSUE TITLE
Improve Javascript-disabled UX

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#815]
## Description
As a user with Javascript disabled, I would like to get relevant search results returned when I search.

## Notes
We can direct users to search.gov-hosted search results

## Acceptance Criteria
- [x] User is directed to the search.gov server-rendered search results page

## Tasks
- [ ] PO approved
- [x] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] ~~Code is properly styled per USWDS~~
- [ ] ~~Finished design has been compared against mockup~~
- [ ] ~~Documentation is complete~~
- [ ] ~~CircleCI tests have passed~~
- [X] Automated accessibility scans have passed
- [ ] ~~Manual accessibility testing completed~~
- [x] Code has been successfully built and deployed into a staging (dev) environment
