### ISSUE TITLE
CircleCI Rate Limiting

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#831]
Build error from rate-limiting from Twitter which we thought had been knocked out a few weeks ago, so we may need to revisit that in CircleCI’s config next week.

## Acceptance Criteria
- [x] HTML-proofer tests pass

## Tasks
- [ ] PO approved
- [ ] ~~Usability tested~~

## Definition of Done
- [x] Pull requests meet technical definition of done
- [ ] ~~Code is properly styled per USWDS~~
- [ ] ~~Finished design has been compared against mockup~~
- [ ] ~~Documentation is complete~~
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [ ] ~~Manual accessibility testing completed~~
- [x] Code has been successfully built and deployed into a staging (dev) environment
