### ISSUE TITLE
Summarize content discovery lessons-learned

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#860]
## Description

As a FAQ team member, I would like a good summary of the pluses and minuses of the FAQ discovery/search process, so I can think cohesively about possible improvements.

## Notes

Add a comment to this ticket, and edit wiki-style.

## Acceptance Criteria
- [ ] Comment on this ticket with notes
- [ ] Links in comment to related-tickets

## Tasks
- [ ] PO approved
- [ ] ~~Usability tested~~

## Definition of Done
- [ ] ~~Pull requests meet technical definition of done~~
- [ ] ~~Code is properly styled per USWDS~~
- [ ] ~~Finished design has been compared against mockup~~
- [ ] Documentation is complete
- [ ] ~~CircleCI tests have passed~~
- [ ] ~~Automated accessibility scans have passed~~
- [ ] ~~Manual accessibility testing completed~~
- [ ] ~~Code has been successfully built and deployed into a staging (dev) environment~~

**Comment by danielnaab** [comment]
_In progress - team members please feel free to edit this comment wiki-style_

# Discovery methods

A quick summary of the current discovery methods of the FAQ content, along with technical dependencies:

* Search engines
    * Static html
* Category pages
    * Static html
* Top-questions
    * Content curation, front-matter
* Search
   * Search.gov (results page)
   * search.json (type-ahead, Fuse.js)

## Search

* Some have expressed confusion on the mismatch between what content is displayed in the autocomplete/typeahead widget vs on the search.gov search results. See original discussion on #170 
    * We did some work to explore making the two consistent - in #774 we tried putting search.gov results in the typeahead, and we could also try using Fuse.js results on the search results page.
* We currently lack some context of what search terms are being displayed on the search results page - see #766, #737 
* search.gov issues
    * `-er` stems - #840 
    * search.gov tracking of clicks by search term - #757
* search.gov routed queries
    * have enabled us to improve search for common terms that return poor results
    * implemented in #736

**Comment by danielnaab** [comment]
Some brainstorming....

Thinking through the above considerations, we could generalize the UI into something that merges category and search results pages into one consistent view, relying on additional content curation and client-side filtering to assist the user in pivoting from interesting questions to related ones.

For instance, assume a use case: the user types "covid information" into Google, and gets a link to the existing category page [https://faq.coronavirus.gov/basics/](https://faq.coronavirus.gov/basics/). On visit, the same category list of questions could correspond to a search filter:

* No search terms
* "About COVID-19" category filter

Behaving in an isomorphic fashion, the filtering could then be modified client-side. The user might type in search terms to drill-down, and have the question list auto-filter on each keypress.

Other actions that may be taken to modify the filtering conditions, putting new filters on the browser's history stack with client-side routing, might include:

* X'ing out the category filter, to apply search terms to the entire FAQ collection
* Clicking direct links to related questions, then the back button to preserve the prior filter
* Clicking category links under questions assigned to multiple categories, to pivot a search to interesting related questions

Additional changes to support this might include modifying the usage of accordions into some kind of expandable card, with the curated links in a standard location.
