### ISSUE TITLE
Upgrade USWDS

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#868]
## Description

We're on USWDS 2.1 - in order to stay up-to-date and take advantage of recent additions, upgrade to the latest USWDS version (currently 2.7.1).

## Acceptance Criteria
- [ ] USWDS 2.7.1 integrated
- [ ] Site stylistically unchanged

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment
