### ISSUE TITLE
Spell out Agency Names

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#873]
Results from content authority research #751 recommend spelling out agency names instead of just showing the acronym, e.g. Centers for Disease Control and Prevention not CDC.   

## Tasks
- [x] How will tackle - change in content, additional meta data, use of agency files. 

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
Reviewed with team on July 7 after standup.  Determined to go with 2 lines with date in italics first and source second.  Deployed to production afternoon of July 7.
