### ISSUE TITLE
Support multiple categories per question

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#887]
## Description
As a user, in order to be fully informed of a topic, I would like to see all questions relevant to a category, including those that may touch on several categories.

## Acceptance Criteria
- [x] Questions have primary category (reflected in their URL)
- [x] Questions can have secondary categories

## Tasks
- [ ] PO approved
- [x] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [x] Documentation is complete
- [x] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment
