### ISSUE TITLE
Upgrade to USWDS 2.8

### ISSUE THREAD

**Issue by danielnaab** [18F/cv_faq#893]
## Description

Upgrade to USWDS 2.8

## Notes
This looks like it will require some attention with, minimally, color contrast.

## Acceptance Criteria
- [x] Version upgraded

## Tasks
- [ ] PO approved
- [x] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [x] Finished design has been compared against mockup
- [x] Documentation is complete
- [ ] CircleCI tests have passed
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment
