### ISSUE TITLE
Data feed of site content

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#896]
## Description
As content admin In order to analyze content performance by agency, I want a feed of all current site questions, their categories, and agency sources. 

## Notes
Sitemap.xml has all desired field elements except for agency(s) for each question.  Adding agencies to sitemap.xml is not valid with extending the namespace. Jona suggested an RSS feed. 

## Acceptance Criteria
- [ ] Feed updated each time site published.
- [ ] Feed contains at minimum URL, question title, category(ties), date and agency(ies).  (Some questions have more than 1 agency.)

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
~Finished design has been compared against mockup~
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment

**Comment by debjudy** [comment]
Dan stated that we have what we need with (https://faq.coronavirus.gov/api/v1/questions.json ).  Closing issue
