### ISSUE TITLE
Strip categories from URL to facilitate canonicalization while supporting multiple categories

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#904]
## Description
As we add in the ability to assign multiple categories to questions, we need to ensure that each FAQ has one true URL  and not multiple URLs (per category) to ensure proper indexation, avoid google penalties for duplicate content, and create succinct, meaningful URLs. 

This should have the benefit of:
- Ensuring the American public can find FAQs that don't fit squarely into a single category
- Allow the FAQ content team to more readily add/edit/publish FAQs that cross category boundaries
- Bolster categories that are lacking in content

## Notes
Need to consider:
- impacts to search.gov indexation, google and other search engine indexation
- most straightforward way to redirect existing FAQs to new canonical URLs
- current [multiple category PR](https://github.com/18F/cv_faq/pull/900)

## Acceptance Criteria
- [ ]

## Tasks
- [ ] PO approved
- [x] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [ ] ~Finished design has been compared against mockup~
- [ ] ~Documentation is complete~
- [x] CircleCI tests have passed
- [ ] ~Automated accessibility scans have passed~
- [ ] ~Manual accessibility testing completed~
- [x] Code has been successfully built and deployed into a staging (dev) environment
