### ISSUE TITLE
Clean up breadcrumb include to reflect current state

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#968]
## Description
As part of the CV-FAQ engineering team, I need the breadcrumb template edited to reflect the desired behavior in order to ensure the next engineer to work on the project does not run into confusion about the commented out, non-functional out code that remained after implementing standalone category yaml files and multi-category content.

## Notes
[Additional context, known dependencies, blockers, links to design documents, etc]

## Acceptance Criteria
- [ ] Breadcrumb include file commented-out code removed
- [ ] Breadcrumb code is legible and understandable

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment
