### ISSUE TITLE
Improve single page question presentation

### ISSUE THREAD

**Issue by debjudy** [18F/cv_faq#983]
When viewing only a single question either via URL or from search results, remove unnecessary elements. 
## Notes

[Average length question](https://faq.coronavirus.gov/are-symptoms-of-covid-19-different-in-children/#are-the-symptoms-of-covid-19-different-in-children-than-in-adults)

[Long question](https://faq.coronavirus.gov/calls-to-small-businesses-promising-quick-financial-relief/)

## Acceptance Criteria
- [ ] Ability to close/open the question removed. 
- [ ] Breadcrumb limited to a single line by breakpoint
- [ ] Figure out and implement multi-category treatment
- [ ] Figure out titles

## Tasks
- [ ] PO approved
- [ ] Usability tested

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Code is properly styled per USWDS
- [ ] Finished design has been compared against mockup
- [ ] Documentation is complete
- [ ] CircleCI tests have passed
- [ ] Automated accessibility scans have passed
- [ ] Manual accessibility testing completed
- [ ] Code has been successfully built and deployed into a staging (dev) environment
