### ISSUE TITLE
Accessibility review

### ISSUE THREAD

**Issue by jonadecker** [18F/cv_faq#996]
## Description
As the producer of the Coronavirus FAQ site, we want to eliminate accessibility errors and alerts wherever possible in order to ensure the site is accessible to the American public.

*Errors*
- [ ] None

*Alerts*
- [x] *Alert:* No h1s on FAQ detail pages. *Fix:* restructure page headings to ensure title is h1 and that any additional headings are semantically correct
- [x] *Alert:* Redundant links. *Fix:* ignorable. These are identical citatations on category pages and occasionally source links that are also linked within the FAQ body
- [x] *Alert:* Links to PDF without alerting to file type or ensuring resulting PDF is accessible. *Fix:* while we cannot control the end PDFs we could consider a pseudoclass on PDFs to identify them and potentially any other external links within the body content (cite/source links are already identified as external links for screenreaders).
- [x] *Alert:* Suspicous link text. *Fix:* the following pages have "click here" or similar link text that should be changed by @18F/cv_flexion_content to apparent link text:
  - /medications
  - /financial-help/is-the-government-delaying-tax-day
  - /support-for-business
  - /medications/are-there-any-vaccines
  - /support-for-business/when-are-taxes-due-for-alcohol-tobacco-firearms-ammunition-businesses
  - /financial-help
  - /support-for-business/employee-retention-credit
- [x] *Alert:* possible header (wants a header where this isn't one). *Fix:* figure out why this is occuring on /protect-yourself/am-i-at-risk-for-covid-19-in-the-united-states. It's also occurring on the home page within the question-box.
- [x] *Alert:* skipped heading level. *Fix:* review the following pages. This may be resolved with some of the earlier heading fixes but it may be ignorable:
  - /financial-help/i-have-not-filed-my-tax-return-for-2018-or-2019
  - /financial-help/what-if-i-cant-complete-my-taxes-by-april-15
  - /symptoms-and-testing
  - /travel
  - /protect-yourself/what-should-i-do-if-i-had-close-contact-with-someone-who-has-covid-19

## Notes
See Jona for additional detail/context and WAVE reports 

## Acceptance Criteria
- [x] Resolvable alerts are fixed

## Tasks
- [ ] PO approved
- [x] Usability tested

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Code is properly styled per USWDS
- [ ] ~Finished design has been compared against mockup~
- [ ] ~Documentation is complete~
- [ ] ~CircleCI tests have passed~
- [x] Automated accessibility scans have passed
- [x] Manual accessibility testing completed
- [x] Code has been successfully built and deployed into a staging (dev) environment

**Comment by jonadecker** [comment]
Updated checklist to resolve unannounced PDFs in body content, suspicious link text, and ignorable items
